#pragma once

#include <QCoreApplication>
#include <QString>

namespace traceview {

// Which communication/transport protocol a device speaks. Only BTP exists
// today (see lib/protocol), but this stays an enum class (rather than a bare
// string) plus a free display-label function below so a second protocol can
// be added later -- one new enumerator, one new commTypeLabel() case -- with
// no API break for anything that already stores/compares a CommType value.
enum class CommType { Btp };

// Human-readable label for a CommType (e.g. the card's comm-type line, see
// devicecard.h). Header-only free function like WidgetRegistry's typeId ->
// displayName mapping (lib/dashboard/widgetregistry.cpp) is at class scope --
// this one isn't a QObject either, so it uses QCoreApplication::translate()
// instead of tr(), same idiom.
inline QString commTypeLabel(CommType type) {
    switch (type) {
        case CommType::Btp:
            return QCoreApplication::translate("Device", "BTP");
    }
    return QString();
}

// One connected/known device, shown as a single card in the Devices panel
// (see devicesgrid.h). Backed by mock/local data for now -- a later phase
// wires real BTP device discovery into this same struct, so it's kept as
// plain public fields (this codebase's low-ceremony value-type style, see
// DashboardItem in dashboard/dashboarditem.h) with no behavior tying it to
// any particular data source. btpVersion/chipType/btpId stand in for
// whatever a real device manifest will report (see DeviceConfigDialog's
// "Reported by device" section).
struct Device {
    QString id;                          // stable identity; auto-generated by
                                          // DevicesGrid::addDevice() if left empty
    QString name;
    bool connected = false;
    CommType commType = CommType::Btp;
    QString description;
    QString btpVersion;
    QString chipType;
    QString btpId;
};

} // namespace traceview
