#pragma once

#include <QCoreApplication>
#include <QJsonObject>
#include <QString>
#include <QVector>

#include "telemetry/deviceinforecord.h"

namespace traceview {

// Which communication/transport protocol a device speaks. Only BTP exists
// today (see lib/protocol), but this stays an enum class (rather than a bare
// string) so a second protocol can be added later -- one new enumerator --
// with no API break for anything that already stores/compares a CommType
// value.
//
// There is deliberately no commTypeLabel() display-string helper: with a
// single enumerator, every place that tried to print one (the card body, the
// config dialog) just showed the bare word "BTP" next to something else
// already saying it. drawCommTypeIcon() (devicecard.cpp) is the one thing
// that still switches on this, and it draws a glyph rather than text. Add a
// label helper back when there is a second protocol to tell apart, not
// before.
enum class CommType { Btp };

// Which physical link a device's connection uses -- independent of CommType
// above (the protocol): BTP can run over either (see BTP's "usb_hid"
// transport profile in docs/fragmentation-and-transports.md section 3.3,
// and lib/core/deviceconnection.h, which is
// the actual switch point). traceview_devices still doesn't depend on
// QSerialPort/hidapi (see lib/CMakeLists.txt) -- this is just a plain enum
// selecting which of Device::portName/usbPath below DeviceConnection should
// use.
// HubChannel is the odd one out and deliberately so: it is not a physical
// link at all, but a channel multiplexed over ANOTHER device's connection --
// a robot reached through the dongle it sits behind (see core/hubtransport.h).
// It lives in the same enum because everything above this layer asks the same
// question of it as of the other two ("which transport does this device
// use"), and DeviceConnection remains the single switch point for all three.
enum class TransportType { Serial, UsbHid, HubChannel };

inline QString transportTypeLabel(TransportType type) {
    switch (type) {
        case TransportType::Serial:
            return QCoreApplication::translate("Device", "Serial");
        case TransportType::UsbHid:
            return QCoreApplication::translate("Device", "USB");
        case TransportType::HubChannel:
            return QCoreApplication::translate("Device", "Hub");
    }
    return QString();
}

// One USB HID device DeviceConfigDialog's picker can offer -- `path` is
// hidapi's own device path (what UsbHidManager::open() expects, not meant
// to be typed by a human), `label` is what the combo box shows instead.
// Lives here (not core/usbhidmanager.h) so DeviceConfigDialog can accept it
// without traceview_devices depending on hidapi -- MainWindow converts
// UsbHidManager::DeviceInfo to this the same way it already converts
// QSerialPortInfo to a bare QStringList for the port picker.
struct UsbDeviceOption {
    QString path;
    QString label;
};

// One hub.peers entry, decoded from the dongle's own live telemetry -- see
// MainWindow::hubPeersFor()/onHubPeerFieldSample() (core/mainwindow.cpp).
// traceview_devices never decodes BTP itself; this arrives as an
// already-reduced value type, same reasoning as UsbDeviceOption above.
//
// `channel` is a DISPLAY INDEX ONLY. The dongle assigns it in the order it
// first hears each peer, and it is not stable across a dongle reboot (see
// bally_dongle's DonglePublisher.h, PeerRecord). DeviceConfigDialog shows it
// as a convenience label; only `sourceId` may ever be written into
// Device::peerSourceId.
struct HubPeer {
    quint32 sourceId = 0;
    quint8 channel = 0;
    QString mac;  // "AA:BB:CC:DD:EE:FF", display only
    quint32 lastSeenAgeMs = 0;
    bool online = false;
    // The boot this robot is currently on, per the dongle's live view. A
    // change here (same sourceId, new bootId) means the robot rebooted -- what
    // MainWindow watches to make a hub child re-request its catalog and
    // re-subscribe without the operator reconnecting it by hand.
    quint32 bootId = 0;
};

// One connected/known device, shown as a single card in the Devices panel
// (see devicesgrid.h), and (as of the multi-device connection refactor) the
// config for one real, independent serial connection -- see
// core/deviceconnection.h, which owns the actual SerialManager/Backend pair
// this data feeds. Kept as plain public fields (this codebase's
// low-ceremony value-type style, see DashboardItem in
// dashboard/dashboarditem.h) with no behavior tying it to any particular
// data source.
struct Device {
    QString id;  // stable identity; auto-generated by
                 // DevicesGrid::addDevice() if left empty
    QString name;
    // Live-mirrored from DeviceConnection::isConnected() by whoever owns the
    // connection (MainWindow) -- not user-editable once a real connection
    // exists. Empty portName means "not configured yet," so this stays
    // false regardless of connection attempts.
    bool connected = false;
    CommType commType = CommType::Btp;
    QString description;
    // What the device reported in its own HELLO_RESULT (protocol/
    // btphandshake.h's sessionEstablished()), surfaced read-only in
    // DeviceConfigDialog's "Reported by device" section -- never
    // user-editable. Live session state, same treatment as `connected`
    // above: reset to empty on disconnect (MainWindow::
    // onDeviceConnectionStateChanged()) and not persisted (deviceToJson()
    // below), since a stale value from a previous device on this port would
    // otherwise linger in a saved project.
    QString btpVersion;
    QString btpId;

    // The device's MANIFEST_DATA source_info block (BTP's docs/commands.md
    // section 3.12): firmware version, chip, running partition, a configured
    // name/description -- shown read-only in DeviceConfigDialog's "Reported by
    // device" section. Same live-session treatment as btpVersion above: filled
    // from Backend::deviceInfoReported, reset to empty on disconnect
    // (MainWindow::onDeviceConnectionStateChanged()), and NOT persisted
    // (deviceToJson()) -- a value from a previous device on this port must not
    // linger in a saved project.
    QVector<DeviceInfoRecord> reportedInfo;

    // Which physical link this device connects over -- see TransportType
    // above. Selects which of the fields below DeviceConnection actually
    // uses; the other stays around unused (harmless, same "keep whatever
    // was there" treatment portName/baudRate/lineTerminator already get
    // when a device isn't configured at all).
    TransportType transportType = TransportType::Serial;

    // Real transport config for this device's connection. Empty portName
    // means "not configured" -- DeviceConnection then never attempts to
    // open a port. traceview_devices can't depend on traceview_ui's
    // QSerialPort-based SerialManager (see lib/CMakeLists.txt layering), so
    // baudRate/portName are plain types here rather than QSerialPort ones.
    QString portName;
    qint32 baudRate = 921600;  // matches the old Run tab's default
    // Ordinal mirroring traceview::LineTerminator (core/serialmanager.h:
    // None=0, Lf=1, Cr=2, CrLf=3) -- kept as a plain int for the same reason
    // portName/baudRate are plain types, rather than depending on that enum
    // directly. Only meaningful for TransportType::Serial (control-widget
    // commands are a raw-text-over-the-console-byte-stream concept that has
    // no equivalent over TransportType::UsbHid, which has no console at
    // all -- see BTP's docs/fragmentation-and-transports.md section 3.3).
    int lineTerminator = 1;  // Lf, matching SerialManager's own default

    // Target for TransportType::UsbHid connections: the hidapi device path
    // (see UsbDeviceOption::path above), analogous to portName for
    // TransportType::Serial. Empty means "not configured," same convention
    // as an empty portName -- DeviceConnection then never attempts to open
    // it.
    QString usbPath;

    // --- TransportType::HubChannel only -----------------------------------
    // A device reached THROUGH another device: a robot behind the dongle it
    // talks to. Ignored entirely by the other two transports, same "keep
    // whatever was there" treatment portName/usbPath already get.

    // Device::id of the hub this one rides. Empty means "not configured".
    QString parentDeviceId;

    // The robot's BTP source_id, and the ONLY thing that may be persisted as
    // its address.
    //
    // ============================ READ THIS ==============================
    // The dongle also publishes a "channel" number per peer (hub.peers), and
    // it is tempting to store that instead because it is short and it is what
    // the UI shows. Do not. That number is a display index assigned in the
    // order the dongle first heard each peer, and it is not stable across a
    // dongle reboot: bring the robots up in a different order and channel 1
    // now names a different one. A project saved with the index would reopen
    // pointing at the wrong robot -- plotting real data, from the wrong
    // machine, raising no error anywhere. A source_id is the robot's own
    // identity and does not move.
    // =====================================================================
    //
    // Zero means "not configured", the safe default a project file missing
    // the field falls back to, and it never connects.
    quint32 peerSourceId = 0;

    // Live-mirrored from the dongle's hub.peers topic by MainWindow while this
    // child is connected -- the same "session state, not configuration"
    // treatment as `connected`/`btpVersion`: not user-editable, not persisted
    // (deviceToJson()), and reset to the defaults below on disconnect.
    //
    // These three together are what deviceLinkState() reads for a hub child,
    // and they are pessimistic by default on purpose. The card must not paint
    // a green "live" dot on the strength of the cable to the dongle alone: a
    // robot can be off, out of range, or never have authenticated a channel-C
    // frame while the hub link itself is perfectly fine. That false-online is
    // the whole reason presence is tracked as its own thing.
    //
    //   peerPresenceKnown  the reconcile has an actual hub.peers verdict for
    //                      this robot (MainWindow::reconcileHubChildPresence).
    //                      False right after connecting and whenever the
    //                      dongle's peer list cannot be read -- the card shows
    //                      amber "locating", never green, until it flips true.
    //   peerOnline         the dongle is currently hearing this robot
    //                      (authenticated channel-C traffic; hub.peers
    //                      online=1). Only meaningful once peerPresenceKnown.
    //   peerLongOffline    peerOnline has held false long enough
    //                      (kOfflineTicksToDeadLink in reconcileHubChildPresence)
    //                      that the child's link is treated as down (red)
    //                      rather than merely stale (amber). Cleared the
    //                      instant the robot is heard again.
    //
    // `peerBootId` lets MainWindow notice a robot reboot.
    bool peerOnline = false;
    bool peerPresenceKnown = false;
    bool peerLongOffline = false;
    quint32 peerBootId = 0;

    // Password for this robot's endpoint key (channel B). Live session input,
    // not configuration -- see cachePeerPassword for whether it is persisted.
    QString peerPassword;

    // Whether peerPassword goes into the saved project.
    //
    // Default false, and that is the important half: a .tvproj is a file
    // people mail to each other and commit, so it must not become a secrets
    // file by accident. Opting in is per device and explicit, for the case
    // where a project lives on one machine and retyping every password on
    // every open is friction with no security bought.
    bool cachePeerPassword = false;

    // --- OTA firmware upload (see lib/ota) -------------------------------
    // A separate Wi-Fi/HTTP side channel bally_OS serves from its DEBUG
    // state (OTAUpdater), independent of whichever transport above this
    // device actually connects through -- a device can be configured for
    // Serial/USB/Hub *and* have an OTA address, since OTA doesn't run over
    // BTP at all.

    // mDNS hostname ("robot1.local") or bare IP the OTA tab targets for this
    // device's GET /status and POST /update. Empty means "not configured for
    // OTA" -- the OTA tab still lists the device, just with nothing to poll.
    // Not a secret, so unlike peerSourceId this is always persisted.
    QString otaAddress;

    // Password for this device's X-OTA-Password header. Live session input,
    // not configuration -- see cacheOtaPassword for whether it is persisted.
    QString otaPassword;

    // Whether otaPassword goes into the saved project. Same opt-in-only
    // convention as cachePeerPassword above, and for the same reason.
    bool cacheOtaPassword = false;
};

// The BTP source_id a hub-channel device speaks as -- its own identity on the
// wire, not the robot's (that is Device::peerSourceId).
//
// Derived from the device's own id rather than generated, because the hub
// needs it to be STABLE. The hub cannot infer where a downstream frame should
// go: a BTP header has no destination field, and TERMINAL_IN carries no target
// in its payload either, so an operator binds child to robot by hand ("hub
// -bind <child> <peer>") and the hub keys that table on the child's source_id.
// A per-run random identity -- which is what this application uses for the
// console channel -- would silently invalidate every bind on every launch.
//
// FNV-1a over the id, forced non-zero because BTP reserves 0. A collision
// between two children would make the hub send one robot's traffic to the
// wrong device, so it is worth knowing the odds: with a 32-bit space and a
// handful of devices they are negligible, and two children of one hub with the
// same source_id would in any case be visible immediately as one of them never
// receiving anything.
inline quint32 hubChannelSourceId(const QString& deviceId) {
    if (deviceId.isEmpty()) {
        return 0;  // "not configured", same convention as an empty portName
    }
    quint32 hash = 2166136261u;
    const QByteArray utf8 = deviceId.toUtf8();
    for (char byte : utf8) {
        hash ^= quint8(byte);
        hash *= 16777619u;
    }
    return hash == 0 ? 1u : hash;
}

// How far this device's link has actually come up -- more than the single
// connected/not bit the card used to paint (topico 35 D.2). The exact
// ambiguity this resolves: a serial device whose port opened but whose BTP
// handshake never completed ("connected and mute") looked identical to a
// working one.
enum class DeviceLinkState {
    Offline,        // no usable link: the transport is down (port closed / not
                    // configured / unplugged), OR a hub child whose robot the
                    // dongle has not heard from for long enough
                    // (Device::peerLongOffline) that the link is treated as
                    // down rather than merely stale
    TransportOnly,  // Serial/UsbHid: link open, but no BTP session yet
    Live,           // BTP session established (Serial/UsbHid), or a hub child
                    // whose robot the dongle is currently hearing
    PeerStale,      // hub child: the cable to the dongle is up, but the robot's
                    // presence is not confirmed live -- either not reported yet
                    // (just connected, or hub.peers unreadable) or last reported
                    // offline but not for long enough to call the link dead
};

inline DeviceLinkState deviceLinkState(const Device& device) {
    if (!device.connected) {
        return DeviceLinkState::Offline;
    }
    if (device.transportType == TransportType::HubChannel) {
        // No ENTER/HELLO on this transport, so `connected` only means the
        // parent session carries this child's frames -- it says nothing about
        // the robot. That comes from the dongle's hub.peers view, mirrored by
        // MainWindow::reconcileHubChildPresence into the peer* fields below.
        // Pessimistic on purpose: unknown or briefly-offline is amber, only a
        // robot the dongle is actually hearing is green, and a sustained
        // silence is red (see Device::peerPresenceKnown / peerLongOffline).
        if (device.peerLongOffline) {
            return DeviceLinkState::Offline;
        }
        if (!device.peerPresenceKnown || !device.peerOnline) {
            return DeviceLinkState::PeerStale;
        }
        return DeviceLinkState::Live;
    }
    // btpVersion is set only by BtpHandshake::sessionEstablished and cleared
    // on disconnect (MainWindow::onDeviceConnectionStateChanged), so it is
    // exactly "a session is up right now".
    return device.btpVersion.isEmpty() ? DeviceLinkState::TransportOnly
                                       : DeviceLinkState::Live;
}

// Mirrors dashboardItemToJson()'s shape/convention (dashboard/dashboarditem.h)
// -- one JSON object per Device, used by DevicesGrid::toJson()/fromJson() to
// persist the whole list into ProjectStore's "devices" section. `connected`,
// `btpVersion`, `btpId` and the `peer*` presence fields are deliberately not
// serialized: they're live-mirrored transport/session state (see each field's
// own comment above), not configuration -- a freshly loaded device always
// starts disconnected and unidentified until DeviceConnection actually opens
// its configured port and negotiates a fresh session.
QJsonObject deviceToJson(const Device& device);

// Returns a default-constructed Device and sets *ok = false if `object` is
// missing required fields.
Device deviceFromJson(const QJsonObject& object, bool* ok);

}  // namespace traceview
