#pragma once

#include <QCoreApplication>
#include <QJsonObject>
#include <QString>

namespace traceview {

// Which communication/transport protocol a device speaks. Only BTP exists
// today (see lib/protocol), but this stays an enum class (rather than a bare
// string) plus a free display-label function below so a second protocol can
// be added later -- one new enumerator, one new commTypeLabel() case -- with
// no API break for anything that already stores/compares a CommType value.
enum class CommType { Btp };

// Human-readable label for a CommType (e.g. the card's comm-type line, see
// devicecard.h). Header-only free function like WidgetRegistry's typeId ->
// displayName mapping (lib/dashboard/widgetregistry.cpp) is at class scope --
// this one isn't a QObject either, so it uses QCoreApplication::translate()
// instead of tr(), same idiom.
inline QString commTypeLabel(CommType type) {
    switch (type) {
        case CommType::Btp:
            return QCoreApplication::translate("Device", "BTP");
    }
    return QString();
}

// Which physical link a device's connection uses -- independent of CommType
// above (the protocol): BTP can run over either (see BTP's ADR 0011, the
// "usb_hid" transport profile, and lib/core/deviceconnection.h, which is
// the actual switch point). traceview_devices still doesn't depend on
// QSerialPort/hidapi (see lib/CMakeLists.txt) -- this is just a plain enum
// selecting which of Device::portName/usbPath below DeviceConnection should
// use.
enum class TransportType { Serial, UsbHid };

inline QString transportTypeLabel(TransportType type) {
    switch (type) {
        case TransportType::Serial:
            return QCoreApplication::translate("Device", "Serial");
        case TransportType::UsbHid:
            return QCoreApplication::translate("Device", "USB");
    }
    return QString();
}

// One USB HID device DeviceConfigDialog's picker can offer -- `path` is
// hidapi's own device path (what UsbHidManager::open() expects, not meant
// to be typed by a human), `label` is what the combo box shows instead.
// Lives here (not core/usbhidmanager.h) so DeviceConfigDialog can accept it
// without traceview_devices depending on hidapi -- MainWindow converts
// UsbHidManager::DeviceInfo to this the same way it already converts
// QSerialPortInfo to a bare QStringList for the port picker.
struct UsbDeviceOption {
    QString path;
    QString label;
};

// One connected/known device, shown as a single card in the Devices panel
// (see devicesgrid.h), and (as of the multi-device connection refactor) the
// config for one real, independent serial connection -- see
// core/deviceconnection.h, which owns the actual SerialManager/Backend pair
// this data feeds. Kept as plain public fields (this codebase's
// low-ceremony value-type style, see DashboardItem in
// dashboard/dashboarditem.h) with no behavior tying it to any particular
// data source.
struct Device {
    QString id;                          // stable identity; auto-generated by
                                          // DevicesGrid::addDevice() if left empty
    QString name;
    // Live-mirrored from DeviceConnection::isConnected() by whoever owns the
    // connection (MainWindow) -- not user-editable once a real connection
    // exists. Empty portName means "not configured yet," so this stays
    // false regardless of connection attempts.
    bool connected = false;
    CommType commType = CommType::Btp;
    QString description;
    // What the device reported in its own HELLO_RESULT (protocol/
    // btphandshake.h's sessionEstablished()), surfaced read-only in
    // DeviceConfigDialog's "Reported by device" section -- never
    // user-editable. Live session state, same treatment as `connected`
    // above: reset to empty on disconnect (MainWindow::
    // onDeviceConnectionStateChanged()) and not persisted (deviceToJson()
    // below), since a stale value from a previous device on this port would
    // otherwise linger in a saved project.
    QString btpVersion;
    QString btpId;

    // Which physical link this device connects over -- see TransportType
    // above. Selects which of the fields below DeviceConnection actually
    // uses; the other stays around unused (harmless, same "keep whatever
    // was there" treatment portName/baudRate/lineTerminator already get
    // when a device isn't configured at all).
    TransportType transportType = TransportType::Serial;

    // Real transport config for this device's connection. Empty portName
    // means "not configured" -- DeviceConnection then never attempts to
    // open a port. traceview_devices can't depend on traceview_ui's
    // QSerialPort-based SerialManager (see lib/CMakeLists.txt layering), so
    // baudRate/portName are plain types here rather than QSerialPort ones.
    QString portName;
    qint32 baudRate = 921600;  // matches the old Run tab's default
    // Ordinal mirroring traceview::LineTerminator (core/serialmanager.h:
    // None=0, Lf=1, Cr=2, CrLf=3) -- kept as a plain int for the same reason
    // portName/baudRate are plain types, rather than depending on that enum
    // directly. Only meaningful for TransportType::Serial (control-widget
    // commands are a raw-text-over-the-console-byte-stream concept that has
    // no equivalent over TransportType::UsbHid, which has no console at
    // all -- see BTP's TRANSPORT_USB_HID.md section 7).
    int lineTerminator = 1;  // Lf, matching SerialManager's own default

    // Target for TransportType::UsbHid connections: the hidapi device path
    // (see UsbDeviceOption::path above), analogous to portName for
    // TransportType::Serial. Empty means "not configured," same convention
    // as an empty portName -- DeviceConnection then never attempts to open
    // it.
    QString usbPath;
};

// Mirrors dashboardItemToJson()'s shape/convention (dashboard/dashboarditem.h)
// -- one JSON object per Device, used by DevicesGrid::toJson()/fromJson() to
// persist the whole list into ProjectStore's "devices" section. `connected`,
// `btpVersion` and `btpId` are deliberately not serialized: they're
// live-mirrored transport/session state (see each field's own comment
// above), not configuration -- a freshly loaded device always starts
// disconnected and unidentified until DeviceConnection actually opens its
// configured port and negotiates a fresh session.
QJsonObject deviceToJson(const Device& device);

// Returns a default-constructed Device and sets *ok = false if `object` is
// missing required fields.
Device deviceFromJson(const QJsonObject& object, bool* ok);

} // namespace traceview
